/**
 * Live drive fixture — the interim "live" producer behind the SSE route until the
 * persistent IssueContainer store lands (Wave-2 ② transport).
 *
 * The keystone of ②: instead of a hand-authored transcript replayed verbatim, the
 * working container's transcript is GENERATED by driveContainer (the pure
 * advance-engine) from a real DriveInput — a PM-distributor DispatchPlan,
 * specialist candidate reports, the diff, and a QA pass. The SSE route streams
 * these steps live (paced via InMemoryContainerStore), so what the Agents console
 * and the Services Synthesizer animate is genuinely the engine's output, not a
 * scripted replay.
 *
 * It is presented in a non-terminal state so the stream PACES (a terminal
 * container replays instantly). The engine already advanced it to `ready`; the
 * `state` here is the live-start snapshot while the transcript animates the solve
 * forward — the same convention the old hand-authored "working" sample used.
 */

import type { DispatchPlan, QaResult } from "@arete/orchestration";
import { driveContainer, type SpecialistReport } from "./driver";
import type { Diff, Finding, IssueContainer } from "./types";

// Must match SAMPLE_INSTALLATION_ID in sample-containers.ts. Inlined to keep this
// module a leaf (sample-containers imports FROM here, not the other way round).
const INSTALLATION_ID = "sample-installation";
const T0 = "2026-07-13T14:00:00Z";
const FILE = "src/billing/webhooks/handlers.ts";

const BASE: IssueContainer = {
  id: "sample-working",
  installationId: INSTALLATION_ID,
  serviceId: "payments-api",
  fingerprint: "payments-api::typeerror::charge()",
  source: "Sentry",
  severity: "critical",
  state: "detecting",
  firstSeen: T0,
  lastSeen: T0,
  occurrences: 3,
  evidence: [
    { key: "error", value: "TypeError: cannot read 'amount' of undefined" },
    { key: "top frame", value: `${FILE}:42` },
  ],
  findings: [],
  transcript: [],
  pr: null,
  gates: { solutionApprovedAt: null, solutionApprovedBy: null, postedAt: null, postedBy: null },
  createdAt: T0,
  updatedAt: T0,
};

// The PM-distributor's analysis + a variable specialist roster (not a fixed six).
const PLAN: DispatchPlan = {
  problemId: "sample-working",
  analysis: "TypeError on charge() — webhook body read before signature verification",
  assignments: [
    { specialty: "root-cause", taskId: "rc", title: "Localize the null deref", owner: "kuma-rc", dependsOn: [], lane: { packages: ["packages/billing"], globs: [] } },
    { specialty: "security", taskId: "sec", title: "Audit webhook signature handling", owner: "kuma-sec", dependsOn: ["rc"], lane: { packages: ["packages/billing"], globs: [] } },
    { specialty: "fix-author", taskId: "fix", title: "Author the guard + verify-first fix", owner: "kuma-fix", dependsOn: ["rc"], lane: { packages: ["packages/billing"], globs: [] } },
    { specialty: "qa", taskId: "qa", title: "Drive the checkout webhook flow", owner: "kuma-qa", dependsOn: ["fix"], lane: { packages: [], globs: ["packages/billing/e2e/**"] } },
  ],
};

function finding(id: string, agentId: string, line: number, rationale: string, confidence?: number): Finding {
  return { id, agentId, category: agentId, file: FILE, line, rationale, diff: [], verdict: "candidate", confidence };
}

const REPORTS: SpecialistReport[] = [
  {
    agentId: "security",
    label: "Security",
    candidates: [
      finding("f-sec-1", "security", 42, "Webhook body parsed before signature verification."),
      finding("f-sec-2", "security", 88, "Possible log of raw payload."),
    ],
  },
  {
    agentId: "business_logic",
    label: "Business Logic",
    // Low confidence → the Synthesizer keeps it but flags "wants a human look".
    candidates: [finding("f-biz-1", "business_logic", 51, "invoice.paid handled without idempotency key.", 0.55)],
  },
];

// Lines 42 and 51 are in the diff (kept); line 88 is not (dropped, unproven).
const DIFF: Diff = [
  { file: FILE, line: 42 },
  { file: FILE, line: 51 },
];

const QA: QaResult[] = [{ pass: true }];

const driven = driveContainer({
  container: BASE,
  plan: PLAN,
  reports: REPORTS,
  diff: DIFF,
  qaResults: QA,
  compose: { base: "main", branch: "arete/fix-sample-working" },
  now: () => T0,
});

/**
 * The working sample container, its transcript produced by driveContainer. Held
 * in a non-terminal state (`fanning_out`) so the SSE route paces the stream.
 */
export const DRIVEN_WORKING: IssueContainer = { ...driven.container, state: "fanning_out" };

export const LIVE_WORKING_ID = DRIVEN_WORKING.id;

/** The interim live source for the SSE route: the driven sample container, or null. */
export function getLiveSampleContainer(id: string): IssueContainer | null {
  return id === DRIVEN_WORKING.id ? DRIVEN_WORKING : null;
}
