/**
 * Sample IssueContainer fixtures — the "sample producer" data source.
 * See docs/superpowers/specs/2026-07-13-synthesizer-component-and-critic.md §4, §5.2.
 *
 * These conform to the canonical IssueContainer type (types.ts). They feed the
 * in-memory ContainerStore so the real SSE path + real component can run before
 * the live Critic / connectors exist. The UI labels anything from here with a
 * "Sample" chip — it is never presented as a real review.
 */

import type { IssueContainer } from "./types";
import { DRIVEN_WORKING } from "./live-drive";

/** Tenant the sample containers live under (no real GitHub installs yet — auth.ts). */
export const SAMPLE_INSTALLATION_ID = "sample-installation";

const T0 = "2026-07-13T14:00:00Z";

// The working (in-flight) sample's transcript is now GENERATED by driveContainer
// and streamed live — see live-drive.ts. This module keeps the terminal DONE
// fixture (history, replayed instantly) alongside it.

const DONE: IssueContainer = {
  id: "sample-done",
  installationId: SAMPLE_INSTALLATION_ID,
  serviceId: "checkout-web",
  fingerprint: "checkout-web::referenceerror::render()",
  source: "Kuma",
  severity: "high",
  state: "posted",
  firstSeen: T0,
  lastSeen: T0,
  occurrences: 1,
  evidence: [{ key: "review", value: "PR #128 — 1 verified finding" }],
  findings: [
    { id: "f-q-1", agentId: "quality", category: "quality", file: "src/checkout/cart.tsx", line: 17, rationale: "Unhandled null before render.", diff: [], verdict: "kept" },
  ],
  transcript: [
    { kind: "dispatch", text: "6 specialists dispatched in parallel", at: T0 },
    { kind: "report", agentId: "quality", text: "Quality reported 1 candidate", at: T0 },
    { kind: "verify", findingId: "f-q-1", agentId: "quality", text: "Verifying Quality · src/checkout/cart.tsx:17", at: T0 },
    { kind: "keep", findingId: "f-q-1", agentId: "quality", text: "Kept — evidence in the diff", detail: "src/checkout/cart.tsx:17", at: T0 },
    { kind: "compose", text: "Composing review — 1 comment", at: T0 },
    { kind: "posted", text: "Pull request opened — PR #128", at: T0 },
  ],
  pr: {
    number: 128,
    base: "main",
    branch: "arete/fix-sample-done",
    title: "Kuma review — 1 verified finding",
    body: "Kuma verified 1 finding against this diff.",
    comments: [{ findingId: "f-q-1", file: "src/checkout/cart.tsx", line: 17, body: "**quality**: Unhandled null before render." }],
    state: "posted",
    hostUrl: "https://github.com/acme/checkout-web/pull/128",
  },
  gates: { solutionApprovedAt: T0, solutionApprovedBy: "you", postedAt: T0, postedBy: "you" },
  createdAt: T0,
  updatedAt: T0,
};

export const SAMPLE_CONTAINERS: IssueContainer[] = [DRIVEN_WORKING, DONE];

/** Stable ids for the sample containers, so UI can reference them without literals. */
export const SAMPLE_WORKING_ID = DRIVEN_WORKING.id;
export const SAMPLE_DONE_ID = DONE.id;

/** True for any container id served by the sample producer — drives the "Sample" chip. */
export function isSampleContainerId(id: string): boolean {
  return SAMPLE_CONTAINERS.some((c) => c.id === id);
}
