"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import {
  IconBriefcase,
  IconGauge,
  IconRocket,
  IconShieldCheck,
  IconSparkles,
  IconTestPipe,
  IconCodeAsterisk,
  IconGitMerge,
  IconBrain,
} from "@tabler/icons-react";
import { cn } from "@/lib/utils";

const AGENT_PROFILES = [
  {
    id: "business-logic",
    label: "Business Logic",
    icon: IconBriefcase,
    color: "#2f55d4",
    tagline: "The Contextual Mastermind",
    importance: "Unlike generic AI, this agent hooks directly into your production telemetry. Real-world business context will always trump generic coding best practices, ensuring fixes don't just compile—they actually make sense for your revenue.",
    synthesizer: "The ultimate trump card. If the Synthesizer attempts to optimize 'dead code', this agent will veto the change if it detects production traffic still hitting that endpoint.",
    example: "Flagged a change to the billing logic because live telemetry showed 15% of Stripe webhooks still rely on the legacy payload format.",
  },
  {
    id: "security",
    label: "Security",
    icon: IconShieldCheck,
    color: "#c2410c",
    tagline: "The Uncompromising Warden",
    importance: "Security vulnerabilities are the most expensive bugs to fix post-deployment. This agent aggressively hunts for OWASP-class flaws, injection risks, and leaked secrets.",
    synthesizer: "Acts as a hard gatekeeper. If the Security agent detects an exploitable flaw, the Synthesizer immediately halts the PR and generates a hardened, sanitized patch.",
    example: "Detected unsanitized user input passed directly to an internal SQL query. Proposed a parameterized query patch to definitively prevent SQL Injection.",
  },
  {
    id: "performance",
    label: "Performance",
    icon: IconGauge,
    color: "#0e7490",
    tagline: "The Efficiency Maximizer",
    importance: "Application speed directly impacts revenue. This agent maps the Big-O complexity of every diff, hunting down memory leaks, N+1 queries, and CPU-bound bottlenecks.",
    synthesizer: "Provides resource-usage metrics. The Synthesizer carefully weighs these metrics against code readability to propose the best balanced optimization.",
    example: "Caught an O(N²) nested loop introduced inside a critical API controller. Rewrote it to use a constant-time Hash Map, reducing load times by 400ms.",
  },
  {
    id: "quality",
    label: "Quality",
    icon: IconSparkles,
    color: "#7c3aed",
    tagline: "The Style Enforcer",
    importance: "Technical debt slowly kills development velocity. This agent ensures your code remains readable, idiomatic, and strictly adheres to your team's architectural standards.",
    synthesizer: "Acts as the formatting filter. It ensures every fix generated by the Synthesizer actually looks like it was written by a senior engineer on your specific team.",
    example: "Refactored a 50-line monolithic function into three highly testable, single-purpose helper methods.",
  },
  {
    id: "test-coverage",
    label: "Test Coverage",
    icon: IconTestPipe,
    color: "#047857",
    tagline: "The Regression Hunter",
    importance: "Code without tests is legacy code. This agent verifies that every newly introduced logic path has corresponding unit, integration, or e2e assertions.",
    synthesizer: "Whenever the Synthesizer proposes a functional fix, this agent is automatically invoked to draft the accompanying Jest or PyTest assertions to prove the fix works.",
    example: "Found an uncovered `if (!user.isActive)` branch. Generated a mock test case asserting the expected 403 Forbidden HTTP response.",
  },
  {
    id: "deployment-safety",
    label: "Deployment Safety",
    icon: IconRocket,
    color: "#b45309",
    tagline: "The Rollout Guardian",
    importance: "Catch infrastructure risks before they bring down CI/CD. It looks for missing environment variables, backward-incompatible DB migrations, and rollout hazards.",
    synthesizer: "Validates the operational reality of the patch. If the Synthesizer drops a database column, this agent enforces a multi-stage migration strategy.",
    example: "Blocked a PR dropping a Postgres column because it didn't use a 'Ignore -> Drop' pattern, which would have caused zero-downtime deployment failures.",
  },
];

export function SpecialistRoster() {
  const [activeId, setActiveId] = useState(AGENT_PROFILES[0].id);
  const [isAutoPlaying, setIsAutoPlaying] = useState(true);
  
  const containerRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(containerRef, { margin: "-100px 0px -100px 0px" });

  // Guard against hydration: defer observer logic until after first client render
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => { setHasMounted(true); }, []);

  useEffect(() => {
    if (!hasMounted || !isInView || !isAutoPlaying) return;

    // Start the first rotation quickly (1.5s) so the user sees movement right away,
    // then settle into the normal 5s cadence for subsequent rotations.
    let isFirst = true;
    let timer: ReturnType<typeof setTimeout>;

    function rotateNext() {
      setActiveId((current) => {
        const currentIndex = AGENT_PROFILES.findIndex(a => a.id === current);
        const nextIndex = (currentIndex + 1) % AGENT_PROFILES.length;
        return AGENT_PROFILES[nextIndex].id;
      });
      isFirst = false;
      timer = setTimeout(rotateNext, 5000);
    }

    timer = setTimeout(rotateNext, isFirst ? 1500 : 5000);

    return () => clearTimeout(timer);
  }, [isInView, isAutoPlaying, hasMounted]);

  const activeAgent = AGENT_PROFILES.find((a) => a.id === activeId)!;

  return (
    <div ref={containerRef} className="w-full rounded-2xl border border-border-subtle bg-surface-1 shadow-lg overflow-hidden flex flex-col sm:flex-row min-h-[600px]">
      
      {/* Left Sidebar: Roster Selection */}
      <div className="sm:w-1/3 border-b sm:border-b-0 sm:border-r border-border-subtle bg-surface-0/50 flex flex-col">
        
        {/* Regular Agents Scrollable Area */}
        <div className="flex-1 flex flex-row sm:flex-col overflow-x-auto sm:overflow-visible">
          <div className="p-4 border-b border-border-subtle hidden sm:block shrink-0">
            <h4 className="text-xs font-semibold uppercase tracking-widest text-content-muted">The Specialists</h4>
          </div>
          
          {AGENT_PROFILES.map((agent) => {
            const isActive = agent.id === activeId;
            const Icon = agent.icon;
            return (
              <button
                key={agent.id}
                onClick={() => {
                  setActiveId(agent.id);
                  setIsAutoPlaying(false);
                }}
                className={cn(
                  "relative flex shrink-0 items-center gap-3 px-5 py-4 text-left transition-colors min-w-[200px] sm:min-w-0 sm:w-full hover:bg-surface-2",
                  isActive ? "bg-surface-2" : ""
                )}
              >
                {isActive && (
                  <motion.div
                    layoutId="active-indicator"
                    className="absolute bottom-0 left-0 h-1 w-full sm:w-1 sm:h-full bg-accent-primary"
                    transition={{ type: "spring", stiffness: 300, damping: 30 }}
                  />
                )}
                <div
                  className={cn(
                    "shrink-0 rounded-lg p-2 transition-colors",
                    isActive ? "shadow-sm" : "bg-transparent"
                  )}
                  style={{ 
                    color: isActive ? agent.color : "currentColor",
                    backgroundColor: isActive ? `${agent.color}15` : undefined,
                  }}
                >
                  <Icon className="h-5 w-5" />
                </div>
                <div>
                  <p className={cn("text-sm font-semibold", isActive ? "text-content-primary" : "text-content-secondary")}>
                    {agent.label}
                  </p>
                  <p className="text-[10px] uppercase tracking-wider text-content-muted hidden sm:block mt-0.5">
                    {agent.tagline}
                  </p>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Right Content Pane: Job Description */}
      <div className="sm:w-2/3 flex-1 bg-surface-1 p-6 sm:p-8 relative">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeAgent.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.2 }}
            className="h-full flex flex-col"
          >
            {/* Header */}
            <div className="flex items-center gap-4 mb-6">
              <div
                className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl border shadow-inner"
                style={{ backgroundColor: `${activeAgent.color}15`, borderColor: `${activeAgent.color}40`, color: activeAgent.color }}
              >
                <activeAgent.icon className="h-7 w-7" />
              </div>
              <div>
                <h3 className="text-2xl font-serif font-semibold text-content-primary tracking-tight">
                  {activeAgent.label}
                </h3>
                <p className="text-sm font-medium" style={{ color: activeAgent.color }}>
                  {activeAgent.tagline}
                </p>
              </div>
            </div>

            <div className="space-y-6 flex-1">
              {/* Role & Importance */}
              <div>
                <h4 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-content-muted mb-3">
                  <IconBriefcase className="h-4 w-4" /> Why they matter
                </h4>
                <p className="text-sm leading-relaxed text-content-primary">
                  {activeAgent.importance}
                </p>
              </div>

              {/* Synthesizer Interaction */}
              <div>
                <h4 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-content-muted mb-3">
                  <IconGitMerge className="h-4 w-4" /> Synthesizer Interaction
                </h4>
                <p className="text-sm leading-relaxed text-content-secondary">
                  {activeAgent.synthesizer}
                </p>
              </div>

              {/* Decision Example */}
              <div className="mt-auto pt-6">
                <h4 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-content-muted mb-3">
                  <IconCodeAsterisk className="h-4 w-4" /> Decision Example
                </h4>
                <div className="rounded-lg border border-border-default bg-surface-0 p-4 shadow-sm relative overflow-hidden">
                  <div className="absolute left-0 top-0 bottom-0 w-1" style={{ backgroundColor: activeAgent.color }} />
                  <p className="text-sm font-mono text-content-primary leading-relaxed pl-2">
                    "{activeAgent.example}"
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
